services:
  npm:
    image: jc21/nginx-proxy-manager
    container_name: nginx-proxy-manager
    ports:
      - "80:80"      # Public HTTP
      - "81:81"      # Admin UI
      - "443:443"    # Public HTTPS
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped